import {
  User,
  Loader2,
  SunMedium,
  Moon,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  Menu,
  Plus,
  Minus,
  Eye,
  EyeOff,
  FileTerminal,
  Settings,
  LogOut,
  ShoppingCart,
  FilePlus,
  Image,
  Search,
  DollarSign,
  GraduationCap,
  Blend,
  X,
  type Icon as LucideIcon,
  type LucideProps,
  ShieldCheck,
  Library,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  user: User,
  spinner: Loader2,
  sun: SunMedium,
  moon: Moon,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronUpDown: ChevronsUpDown,
  menu: Menu,
  add: Plus,
  remove: Minus,
  view: Eye,
  hide: EyeOff,
  terminal: FileTerminal,
  settings: Settings,
  logout: LogOut,
  cart: ShoppingCart,
  search: Search,
  placeholder: Image,
  dollarSign: DollarSign,
  file: FilePlus,
  cap: GraduationCap,
  brand: Blend,
  library: Library,
};
